version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ihsan_db
    restart: always
    environment:
      POSTGRES_USER: ihsan
      POSTGRES_PASSWORD: ihsan
      POSTGRES_DB: ihsan_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: